version: '3.7'

services:
  openldap:
    container_name: ${NAME}
    image: ${IMAGE}:latest
    ports:
      - 3000:3000
    environment:
      LDAP_ADMIN_PASSWORD: admin
      LDAP_BACKEND: 'mdb'
      LDAP_BASE_DN: ''
      LDAP_CONFIG_PASSWORD: config
      LDAP_DOMAIN: example.org
      LDAP_HASH_PASSWORD: 'true'
      LDAP_LOG_LEVEL: '256'
      LDAP_ORGANISATION: 'Example Inc.'
      LDAP_READONLY_USER: 'false'
      LDAP_READONLY_USER_PASSWORD: readonly
      LDAP_READONLY_USER_USERNAME: readonly
      LDAP_REPLICATION: 'false'
      LDAP_RFC2307BIS_SCHEMA: 'false'
      LDAP_TLS: 'true'
      LDAP_TLS_CA_CRT_FILENAME: ca.crt
      LDAP_TLS_CIPHER_SUITE: SECURE256:-VERS-SSL3.0
      LDAP_TLS_CRT_FILENAME: ldap.crt
      LDAP_TLS_ENFORCE: 'false'
      LDAP_TLS_KEY_FILENAME: ldap.key
      LDAP_TLS_PROTOCOL_MIN: '3.1'
      LDAP_TLS_VERIFY_CLIENT: demand
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #docker-compose.ymlLDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: 'false'
      LDAP_REMOVE_CONFIG_AFTER_SETUP: 'false'
      LDAP_SSL_HELPER_PREFIX: ldap
    tty: true
    stdin_open: true
    # volumes:
    #   - /var/lib/ldap
    #   - /etc/ldap/slapd.d
    #   - /container/service/slapd/assets/certs/
    ports:
      - '389:389'
      - '636:636'
    domainname: example.org # important: same as hostname
    hostname: example.org

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - 8080:80
    depends_on:
      - openldap

volumes:
  openldap:
    name: openldap-${NAME}
