version: "2"

services:
  build:
    image: ${IMAGE}:${TAG}
    build:
      context: latest
      dockerfile: Dockerfile
  major:
    extends: build
    image: ${IMAGE}:${MAJOR}
  minor:
    extends: build
    image: ${IMAGE}:${MAJOR}.${MINOR}
  patch:
    extends: build
    image: ${IMAGE}:${MAJOR}.${MINOR}.${PATCH}
